### ISSUE TITLE
[Bug] All Plugins option on source menu brings back only wii games on beta build

### ISSUE THREAD

**Issue by OoIceDeepoO** [Fledge68/WiiFlow_Lite#130]
Hi,

Super simple source_menu.ini 

[BUTTON_0]
image=Plugins.png
image_s=Pluginsb.png
title=All Plugins
source=allplugins
emuflow=1

[BUTTON_1]
image=Gamecube.png
image_s=Gamecubeb.png
title=Gamecube
source=dml
magic=
emuflow=

[BUTTON_2]
image=Wii.png
image_s=Wiib.png
title=Wii
source=wii
magic=
emuflow=

When selecting All Plugins, the only games displayed are wii games, no gamecube games will display. I tried this with other plugins. Switched the order of the buttons. Same result. This does not happen on 5.2.0. I am on the beta build you sent me for the categories bug and only seems to happen on this beta build. I wanted to let you know so it does not creep into an official release..

Let me know if you want any deeper testing.

**Comment by Fledge68** [comment]
not a bug. See this commit two weeks ago - https://github.com/Fledge68/WiiFlow_Lite/commit/50667245061592643bbf4250d46ac024e0832bd5

I removed all plugins because there really seems no need for it.  you can either go to Select Plugin button and click the All button till every one has a checkmark. or create a source button  with all the magic #'s separated by a comma.
