### ISSUE TITLE
Unable to install wiiflow

### ISSUE THREAD

**Issue by RS0087** [Fledge68/WiiFlow_Lite#172]
Hello,

Im trying to install wiiflow from home-brew channel, however when I click the wiiflow installer in home-brew the wiiflow logo pops up like its loading but then just quits back to the home-brew menu. I looked at the files in the apps folder and it appears the latest release does not have the wiiflowlite.ini file, is this the issue? Thank you!

**Comment by Fledge68** [comment]
on very first boot up there is no wiiflow lite.ini. but wiiflow will make one but only save it to your apps folder once you launch a game or you properly exit wiiflow.

and you don't install wiiflow from the homebrew channel. you launch it from the homebrew channel after you manually install wiiflow by putting all the files in the correct folders supplied in the download zip.

**Comment by RS0087** [comment]
I did place the wiiflow folder in the apps folder which is on the root of my sd card, however it will just bring up the wiiflow start screen then immediately exit to the home-brew menu

**Comment by gingerbeardman** [comment]
Do you have any games on your SD/USB?

**Comment by Fledge68** [comment]
did you copy the other folders in the zip?
the wiiflow folder and plugin data and coverflow folders?

**Comment by RS0087** [comment]
Yes I have GameCube games on the sd under the games folder in the root of the sd, I copied the wiiflow folder to the apps folder on the root, and the other wiiflow folder with the plugins I copied to the root of the sd card

**Comment by Fledge68** [comment]
run wiiflow start configurator and set force cios off.
http://www.mediafire.com/file/2h1stwpdvd3r04q/wf_start_config.zip/file

**Comment by guitaristtom** [comment]
I'm having this issue on my WiiU as well

**Comment by wuniversales** [comment]
Something similar happens to me when starting wiiflow from the homebrew channel.
WiiFlow does not start me with the pendrive on USB 1, it only starts me with the pendrive on USB 0.

Connecting the pendrive ...
- On USB 1, when you start it, the homebrew channel opens.
- USB 0 works correctly for me.

On the other hand, with the USB stick connected to 1, I have tried using "wiiflow start configurator" to change from 0 to 1, but there is no way, it does not start ...

If I put it to 0, or 1, they both boot USB 0, I don't know why strange reason this happens ...

Could it be because USB 0 has Wii Speak connected, and USB 1 the USB stick?

However it works correctly on the contrary.
On USB 1 Wii Speak, and on USB 0 the USB stick ...

**Comment by Fledge68** [comment]
you should always have usb hdd (or in your case usb stick) plugged in usb  0. only specific cios allow you to use usb 1. 

usb 1 goes to HBC because wiiflow is failing to start. on fail to start wiiflow exits to HBC. I know it's weird and i have fixed this in the latest commit.
usb 0 works because that is the correct port and all cios work with it.

if you put it to 1 and it still boots usb 0 thats because wiiflow sees you don't have right cios for usb 1 and automatically switches to usb 0.

now if you turn force cios off wiiflow uses ios58. and ios58 can read both ports.
that's why the forwarder and hbc are able to see and boot wiiflow even if using usb 1.
but since 5.4.0 (i think) i made wiiflow default to using cios. so once wiiflow boots if you don't have the right cios wiiflow can't find itself or your usb device.  you need to either use usb 0 or use start config to set force cios off. 

now ios58 sounds great. but it isn't compatible with all devices or may be unreliable. 

cios d2x 10 beta 53 is both ports capable but unreliable with nand emulation.
cios d2x 10 beta 52 only works with port 0 and is basically the same as d2x v8.

**Comment by Fledge68** [comment]
closing because i have not heard anything for quite some time.

**Comment by YeetyDankEngine** [comment]
Hello I am having this issue

**Comment by gingerbeardman** [comment]
@YeetyDankEngine did you do the troubleshooting above? How did it go? Let us know your results and details of your setup.

**Comment by YeetyDankEngine** [comment]
yes i did try but the start config just crashed, somethimg about a dump. also, how do i run a syscheck

**Comment by YeetyDankEngine** [comment]
USB loader gx and CFG loader also not working

**Comment by gingerbeardman** [comment]
Then I think you have bigger problems.

- Please check your Wii is modded correctly, maybe mod it again using ModMii
- And if you're using a hard drive that it is formatted, plugged and powered correctly
- Maybe try using SD card first instead of hard drive

We cannot offer you much more assistance without WFL specific details.

GBAtemp or a Wii modding Discord may be better for wider support.
