### ISSUE TITLE
WiiFlow not loading / detecting the storage?

### ISSUE THREAD

**Issue by guitaristtom** [Fledge68/WiiFlow_Lite#174]
For some reason, even though WiiFlow is stored on my SD card, it's not detecting the SD card and looking all funny.

I tried using the exact same SD card in my Wii, and it is working and showing up just fine, it's just when it's in the WiiU.

![image](https://user-images.githubusercontent.com/6890628/80305581-5a589e00-8772-11ea-9064-f5e309996675.png)

and here is the home screen:
![image](https://user-images.githubusercontent.com/6890628/80305590-680e2380-8772-11ea-97e5-b399c8aa42a7.png)

If there is any info you need, just ask.

**Comment by Fledge68** [comment]
it's got to be the vwii cios you have installed in slot 249.
don't use beta53 alt.
and using base 57 or 58 works better.

otherwise if you can get to the main settings>startup settings try setting force cios to off. doing that will make wiiflow use ios58 instead of cios. the only problem might be when you try to launch a wii or emunand game it may not work because wiiflow must switch to cios to launch those type of games and doing that sometimes loses USB  HDD connection.

**Comment by guitaristtom** [comment]
I ended up using the vWii Modding section of https://wiiu.hacks.guide back when I initially hacked my vWii. This was before the handover to the Nintendo Hacking Discord group though (who seem to have done a revamp on it).

According to my Syscheck, I'm using `d2x-v10beta53-alt-vWii`. As you mentioned that is probably the issue. I'll reinstall it and see if that is the issue.

**Comment by guitaristtom** [comment]
Looks like installing beta52 fixed the issue. I don't know why I didn't think to check that... Thank you.

I honestly don't use my WiiU for a whole lot, and tend to prefer using my standard Wii instead of it for Wii games.
