### ISSUE TITLE
Ignores proxy setting in WiFi profile

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#195]
Internet access is only possible via a proxy, which is why a proxy is configured in the WiFi profile on Wii. WiiFlow tries to bypass the proxy to obtain data from the Internet (cover, title db etc). which fails as expected.

**Comment by wiidev** [comment]
The libogc networking code is incomplete and doesn't provide many of the necessary functions, so you'll experience this problem with all Wii homebrew.

I'm working on an update that adds support for HTTPS proxies, but you'll need to enter the proxy details into the WiiFlow config file instead.

**Comment by eku** [comment]
> but you'll need to enter the proxy details into the WiiFlow config

What's wrong with reading the values directly from the Wii settings?

**Comment by wiidev** [comment]
@eku I found out how to retrieve the proxy settings from the system, so that'll be an option soon. And in WiiFlow's settings menu you'll see an option called "Use system proxy settings", which when disabled will load the proxy settings from WiiFlow's config file instead.

The Wii is limited to using just HTTP and HTTPS proxies, but you can connect your PC to a VPN and then use software like [mitmproxy](https://mitmproxy.org/) or the free version of CCProxy. You can then connect your Wii to your PC's proxy server.

During testing I used mitmproxy and changed stream_large_bodies to 1m.

**Comment by eku** [comment]
> I found out how to retrieve the proxy settings from the system

Would you share  the information with the USB Loader GX developers as their loader has the same problem?

**Comment by wiidev** [comment]
@eku I'm the developer for the [enhanced version](https://gbatemp.net/posts/8856063) of USB Loader GX. I'll be releasing an update that adds proxy support within the next few days.

**Comment by wiidev** [comment]
@eku I developed the [enhanced version](https://gbatemp.net/posts/8856063) of USB Loader GX. I'll be releasing an update that adds proxy support within the next few days.

**Comment by Fledge68** [comment]
this has been fixed in a recent commit so i'm closing it.

**Comment by eku** [comment]
> this has been fixed in a recent commit so i'm closing it.

Hmm, could you please link to the commit hash in this issue?

**Comment by gingerbeardman** [comment]
https://github.com/Fledge68/WiiFlow_Lite/pull/200/commits/a80d629859e44a4861b8d4eb8708c855b6e01089
