### ISSUE TITLE
Advantages over GX?

### ISSUE THREAD

**Issue by fancymelonub** [Fledge68/WiiFlow_Lite#2]
Is there any advantages using this over GX? I know GX has a "Prviate Server" thing and others.
Is there any cool features WiiFlow Lite has that might make me use it as at least a secondary? Also, it's annoying that WiiFlow Lite defaults to the SD instead of USB for games.

**Comment by Fledge68** [comment]
wfl advantages over gx - the full 3d coverflow instead of the boring flat 2d or 3d covers and plugin mode. other than that wfl can pretty much do whatever usbloadergx can including the private server.

wfl defaulting to SD instead of USB for games - good point. maybe i should set to USB if a USB device is attached. right now i believe it defaults to SD if wfl itself is on SD.

**Comment by gingerbeardman** [comment]
https://gbatemp.net/threads/backup-loaders-comparison-chart.333364/
