### ISSUE TITLE
[BUG] music looping can crash download/conversion/long processes

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#21]
See 

#19 crash whilst reloading cache / converting covers
#20 crash whilst downloading covers

workaround would be to stop music during these long processes

better solution would be to fix the problem

**Comment by Fledge68** [comment]
yes i'm aware of this. i had hoped it had fixed itself but i guess not. i had music and other stuff shut off before but reenabled it this time cause it seemed to be working. guess not.

either because bg music uses multithreading or somewhere music is using memory that conflicts with the downloading or cover converting. i'll try stopping music again and see if that helps.
