### ISSUE TITLE
ntfs partition 2 (containing the wbfs folder) changed at startup

### ISSUE THREAD

**Issue by LukeZS** [Fledge68/WiiFlow_Lite#260]
I have no SD, only a USB disk with 2 partitions: primary formatted FAT (partition 1) and logic formatted NTFS (partition 2).

My wiiflow_lite.ini contains this:

[WII]
current_save_emunand=default
favorites=no
fix480p=no
last_cf_mode=1
**partition=2**
prefer_usb=yes
save_emulation=0
**savepartition=2**
show_full_banner=no
sort=0
wii_games_dir=%s:/wbfs

But when I start my WII, it says it doesn't find the **usb1:/wbfs** path. If I manually change within the WiifloLite menu the WII games partition to usb2, it works, but the wiiflow_lite.ini is changed this way:

[WII]
current_save_emunand=default
favorites=no
fix480p=no
last_cf_mode=1
**partition=1**
prefer_usb=yes
save_emulation=0
**savepartition=1**
show_full_banner=no
sort=0
wii_games_dir=%s:/wbfs

I don't know why it changed partition and savepartitions, but i don't think it should do it.

**Comment by gingerbeardman** [comment]
This is saying you want to use the partition for loading and for saving (save games).

**Comment by LukeZS** [comment]
Yes, but it's changed (from 2 to 1) after boot...

**Comment by gingerbeardman** [comment]
It changed in the ini because you changed it in the WFL menu.

**Comment by LukeZS** [comment]
Nope. I didn't change anything in the Wiiflow Menu.

**Comment by gingerbeardman** [comment]
But you said

> *If I manually change within the WiifloLite menu* the WII games partition to usb2, it works, but the wiiflow_lite.ini is changed this way:

**Comment by Fledge68** [comment]
Ha! after all these months i decided to look into this issue and its easy to see the problem.

you have - prefer_usb=yes

setting it to 'no' will solve your problem. my code problem is it sets the partition to 'USB1' when a usb device is connected. I have no way of knowing you prefer 'usb2'.

it was added because gingerbeardman sometimes disconnects his usb drive which causes wiiflow to think he wants SD only so when he reconnects his hard drive he had to manually turn of sd only and set partition back to usb1. I'll look into a better way to fix this.

**Comment by gingerbeardman** [comment]
Thanks! And sorry to inadvertently be the cause of this one 😅
