### ISSUE TITLE
Crash, updating from version 5.4.1

### ISSUE THREAD

**Issue by inforemberto** [Fledge68/WiiFlow_Lite#268]
Hello,

DEVICE: Wii v4.3u

I am currently using version 5.4.1. I have tried updating to version 5.4.8 and 5.4.9 and it always fails.

I deleted all the folders and put the new ones.
/ app / wiiflow
/ wiiflow

Wiiflow displays the screen but closes before displaying games.

Is it necessary to update any CIOS or does it have any dependencies?

I can send you the files from my SD card if you need to check any settings or parameters.

Thanks for the great job you do.

**Comment by Fledge68** [comment]
1. try deleting the wiiflow save game file when you delete all the old files. OR
2. try using wiiflow start configurator  found here - https://www.mediafire.com/file/vdchnzz8nh587g1/Wiiflow_Start_Configurator.zip/file - use it to change force ios on/off or if ON switch the cIOS used. it will change the wiiflow save game file so that hopefully the next time you boot wiiflow 5.4.9 it will work for you.
