### ISSUE TITLE
[BUG] download cover on game setting view does not get all covers

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#27]
- Add new game
- goto Wii view
- Refresh cache
- Click on new game
- Click cog
- Download cover

Expected
- box cover and HQ covers should be downloaded

Actual
- only low resolution front cover is downloaded

**Comment by gingerbeardman** [comment]
This also applies to "Download Missing" in main settings. 

It's only "Download All" in main settings that downloads the expected covers

**Comment by Fledge68** [comment]
wiiflow only downloads one cover.
first try is full (box) cover HQ
if not - then 2d flat cover.
no need for both.

on missing only - if full cover exist then game is not added to missing list.

**Comment by gingerbeardman** [comment]
Hmm. I see. 

My situation is that I have not been able to download the HQ box cover (I checked manually to prove it exists) for a newly added game by choosing "download missing" on either game setting page or main menu. 

I'm reluctant to do "download all" again as it takes a long time for me

**Comment by Fledge68** [comment]
can you tell me what game(s)?
and provide download links that work on pc so i can compare them to the url wiiflow uses.

**Comment by gingerbeardman** [comment]
Skylanders SuperChargers Racing was one I had to manually copy the full cover earlier today
https://www.gametdb.com/Wii/SKNP52

**Comment by gingerbeardman** [comment]
But try adding a any new game that has a full cover on gametdb and then - without doing "download all" - try to get a full cover downloaded for it.

**Comment by Fledge68** [comment]
hey here is wfl v5.0.1 with the latest commits.
[http://www.mediafire.com/file/w1u2qlme6cpvlnc/wfl5.0.1_boot.dol/file](url)
try the cover downloading and reload cache.

**Comment by gingerbeardman** [comment]
with that 5.0.1 build

- hard crash (reload type) when deleting cover from game settings

- download/reload works from plugins view now notices new games
- download cover from game settings still only gets 2D front
- download all/missing did not pick up full cover for SKNP52

- progress bar now seems to be accurate for downloads
- progress bar still inaccurate for "converting covers" process after reload cache

good progress!

**Comment by Fledge68** [comment]
i don't believe your hard crashes.
deleting cover - just deletes a couple of files on your sd or usb. nothing there should cause a crash.
install game - doesn't even work. all it does is display a message that it doesn't work try clean rip.
so something you did before them must've screwed up wiiflow.

download cover from game settings uses the same code as download all and missing so i don't see how it can only get 2d front, yet all or missing do get full. 

as for skylanders - strange that's the only game - must be a mistake on gametdb's part because the download link wiiflow uses is different than that's on pc. maybe you or i can try to download it with usbloader gx.

and i personally don't have any issue with progress bar for converting covers. it always shows a 100%

i think you are right about download all or missing. they are basically the same. i either need to get rid of one or make all delete any full cover first and then redownload it. but i don't see any reason for someone to want to do that.

**Comment by gingerbeardman** [comment]
Oh! Good spot. Has this been fixed at gametdb? I can't see that on gamdtdb
