### ISSUE TITLE
[Discussion] Refactor WFL - replace C with C++

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#280]
Apart from some loaders, WFL is written in C++. So much for the theory. In practice, the source code uses more C instead of C++ code and constantly converts strings back and forth, for example.

For new source code, the rule should be to use only pure C++. All standards up to and including C++20 have extended the language well, so there is no need for pure C.

Existing source code should be refactored carefully if a file or class is edited anyway for enhancements and bug fixes.

**Comment by Fledge68** [comment]
not interested.

1. i stepped away from wiiflow coding since april and only came back recently because i seen blackb0x's progress with usb loader gx and felt the need to add a few things.
2.  my understanding is when your coding for wii you want to primarily use C as much as possible because it is low level, sometimes faster and can produce smaller code. And that's why it's normally used for embedded devices that typically don't have a fast CPU or a lot of memory such as the wii. even libogc uses C

**Comment by gingerbeardman** [comment]
My understanding also aligns with 2, fwiw.
