### ISSUE TITLE
[Enhancement] Change config folder location from "wiiflow" to "wiiflow_lite"

### ISSUE THREAD

**Issue by DraconicNEO** [Fledge68/WiiFlow_Lite#282]
I feel like we should change the location of the main folder from `wiiflow` to `wiiflow_lite`. I feel like this would be helpful since it could allow people to have Wiiflow lite installed alongside Wiiflow and to help distinguish between them since Wiiflow themes and plugins aren't compatible with Wiiflow Lite. Also it would make sense since we already changed the location of the app folder to `/apps/wiiflow_lite/`.

**Comment by Fledge68** [comment]
so this is hard to explain. but when you get down to it wiiflow lite is basically just wiiflow from where fix94 left off. I was one of the contributing devs of wiiflow back when fix94 was the main dev.  but when i decided to get back into coding wiiflow i did so without talking to fix94 so I felt I needed to give it a different name. after a while it was clear fix94 was done with wiiflow and everyone seemed to like wiiflow lite so i changed the name back to wiiflow and make everything much simpler. 

plus there's really no point in using the old wiiflow 4 anymore since it hasn't been updated since 2013 and like i said wiiflow lite IS wiiflow. and by the way we don't use apps/wiiflow_lite anymore. we do still use wiiflow_lite.ini

Also wiidev's usb loader gx enhanced is his version of usb loader gx but he still uses usb loader gx.

**Comment by DraconicNEO** [comment]
> 
> 
> so this is hard to explain. but when you get down to it wiiflow lite is basically just wiiflow from where fix94 left off. I was one of the contributing devs of wiiflow back when fix94 was the main dev. but when i decided to get back into coding wiiflow i did so without talking to fix94 so I felt I needed to give it a different name. after a while it was clear fix94 was done with wiiflow and everyone seemed to like wiiflow lite so i changed the name back to wiiflow and make everything much simpler.

Oh, I see. So essentially this is the main build of Wiiflow. 

> plus there's really no point in using the old wiiflow 4 anymore since it hasn't been updated since 2013 and like i said wiiflow lite IS wiiflow. and by the way we don't use apps/wiiflow_lite anymore. we do still use wiiflow_lite.ini

Wait so we don't use `/apps/wiiflow_lite` anymore? Was that a recent descision because I noticed that the latest debug builds that it still says wiiflow_lite as the app folder name.

> Also wiidev's usb loader gx enhanced is his version of usb loader gx but he still uses usb loader gx.

I thought his version was meant to be a continuation version due to the Fact that cyan lost interest in the original version long ago.

**Comment by Fledge68** [comment]
you should probably read the Readme which is on the first page if you scroll down
