### ISSUE TITLE
Wiiflow Not Caching All .Cue Titles

### ISSUE THREAD

**Issue by whitezombie455** [Fledge68/WiiFlow_Lite#344]
I've noticed a bug with wiiflow where it will not generate cache files for some games that are .cue. Most show up but some randomly don't. Even after using a program to manually generate the cache files in wiiflow cache folder the files still don't show up even after a reload cache.

**Comment by Fledge68** [comment]
your problem is probably the regex default. it's been updated since v5.5.3

look in wiiflow_lite.ini for [PLUGINS] filename_skip_regex=
and change it to
((dis[ck]|tape|side|track)[ _-]([b-l][^a-z]|0*[2-9]|0*[1-9][0-9]))|(^disc2[.]iso$)|(^neogeo[.]zip$)|(^funboot[.]rom$)|(^(ecs|exec|grom)[.]bin$)

and do a reload cache.

**Comment by whitezombie455** [comment]
That fixed it! Not sure why my wiiflow_lite.ini is out of date when I am running v5.5.3 but I appreciate it!
