### ISSUE TITLE
[BUG] vwiinands folder cannot be used

### ISSUE THREAD

**Issue by goplaycheckers** [Fledge68/WiiFlow_Lite#84]
I feel like I've tried everything at this point...

I finally have neek2o working (r96 beta 9.6) on WiiU vWii. I can launch my nand using the neek2o forwarder channel and the nand loads as expected. However, WiiFlow (I'm running 5.2.0) ONLY looks in the drive:\nands folder and does not seem to observe any kind of custom nand path that WiiFlow [used to honor](https://sites.google.com/site/wiiflowiki4/emu-nand-and-neek2o) in the ini file. As far as I can tell from the limited information floating around on neek2o with vWii, all nands must exist in vwiinands folder, and there is apparently no way to tell neek2o on vWii to use the \nands path. 

I understand that WiiFlow supported vWii + neek2o r96 beta 9.6 at one point (see [this post](https://gbatemp.net/threads/wiiflow-lite.422685/page-8#post-7310567)), but there must have been a reversion in the code, or (fingers crossed) I'm overlooking some undocumented setting somewhere. 

Due to the issue above, I can either 1) put this nand in \vwiinands and launch my nand via the neek2o forwarder, but I lose this nand in WiiFlow, or 2) move this nand to \nands which shows it in WiiFlow but neek2o no longer works. I have also tried making a duplicate of this nand and placing it in the \vwiinands and \nands folders so WiiFlow could theoretically see AND launch it, but while WiiFlow can see it, it cannot launch a title in neek2o mode.

Would it be possible to get a simple toggle option for \nands vs \vwiinands in the settings, or at the very least, a switch in the config file, to fix this issue?

Thanks in advance!

**Comment by Fledge68** [comment]
strange ... i coded wiiflow (lite) some time ago so that when on wiiu the nands folder had to be vwiinands. how is it your using nands folder and apparently wiiflow doesn't show nands in the vwiinands folder?

**Comment by goplaycheckers** [comment]
To clarify:

I can place a nand in \nands and WiiFlow will see it, I can use it as an
emunand, but neek2o is completely nonfunctional.

I can then move that nand to \vwiinands, at which point neek2o works (I can
launch it from the neek2o forwarder channel) but WiiFlow does not see it at
all and will not launch the nand from the neek2o option in the Home button
menu in WiiFlow.

Does that make sense?

**Comment by Fledge68** [comment]
Had a chance to test this out today. wiiflow (lite) does indeed find the nands listed in vwiinands folder. it must be on USB1.
goto main settings>partition settings and set emu nand partition to usb1.
goto main settings>emunand settings and select your emunand.
when you go back to the main screen wiiflow should do auto reload cache.

upon wiiflow boot it will detect if you are on wii or wii u. if wii the nands folder is 'nands' on wii u it is 'vwiinands'

But there does seem to be a problem. 
i launched a Wiiware game without neek2o and wiiflow ran it no problem except it crashed when returning to wiiflow. (that would be a diferent issue)
i launched it again this time with the neek2o option on. It just black screened. I used neek2o r96 beta9.6 but it wouldn't do anything. neek2o's instructions make it sound like you need an actual vWii nand dump. that wii nands won't work.

**Comment by shawksly** [comment]
I sincerely apologize if this is the wrong place to post this, but I'm just elated! After 3 days of ~5 hours each trying to solve my own problem, I finally found someone else with a description of my **exact** issue here.

However -- and this is the reason I thought it might be worth posting in this bug -- this is happening on a regular Wii for me. I have emunand all set up. I can load into it via the armboot with bootmii, or with nswitch, and I can play any games from their channels. And WiiFlow will load non-problematic VC and WiiWare titles perfectly.

However, the neek2o channel forwarder does not work in real nand, and once I turn neek2o switch on for WiiFlow, I get a black screen that lasts forever.

I'm not convinced that this is a WFL bug, since the issue seems to extend to the neek2o forwarder channel. But I think this does show that it's not just a Wii U issue.

I wrote more info about my situation (with SysChecks) here: [https://gbatemp.net/threads/completely-stuck-with-neek2o-and-wiiflow.572571/](url)

Thanks for your help, and your incredible work! And sorry again if this is not the right place to post. Please feel free to delete it.

**Comment by shawksly** [comment]
Well, forgive me. It turns out that I needed BoomMii installed as ios and that fixed my issues. So disregard my previous comment unless it's helpful to you. Thanks again for all your amazing work!
