### ISSUE TITLE
Autoboot doesn't work when homebrew name length > 15

### ISSUE THREAD

**Issue by iamerror80** [Fledge68/WiiFlow_Lite#85]
The source menu autoboot feature doesn't work with homebrews that name (apps/folder) exceeds 15 chars (e. g. "apps/SaveGame_Manager_GX" won't work but "apps/SaveGame_Manage" works fine).

Also I noticed that when using a theme that name exceeds 15 chars, Wiiflow will reboot each time after you quit Settings menu, as it does when it has to reload a new theme, even if you didn't modify anything.

**Comment by Fledge68** [comment]
very strange. in both situations the names are not limited to 15 chars. in homebrew autoboot it is 63 chars. the only thing i can see is the code is using const char *name= getString().c_str(). I have had this type of code cause issues in the past. for some reason converting the string to c_str and then setting a const char * to the c_str causes messed up or empty strings. not sure why 15 char limit makes it work.

i will rewrite the code to use strings instead of c_str's or use char arrays.

**Comment by Fledge68** [comment]
could you guys please try this one.

[https://www.mediafire.com/file/gvkh6yu88eei88e/boot.dol/file](url)

**Comment by iamerror80** [comment]
Fixed :-) Thanks !
