### ISSUE TITLE
Set Standby options

### ISSUE THREAD

**Issue by dispetto77** [Fledge68/WiiFlow_Lite#91]
Hi at all

Is there a way to don't ignore stanby when i press on/off button?
Now when I press ON/OFF button on the wii , wiiflow turn directly off the wii (red led)
I would like it goes in standby (yellow led)

thanks

**Comment by gingerbeardman** [comment]
Related #29

**Comment by dispetto77** [comment]
> Related #29

I saw that post.  But since from 4.02 the standby is bypassed from wiiflow, i'm asking if there is a way to enable it again

**Comment by gingerbeardman** [comment]
@dispetto77 understood, related issues are just so similar problems can be tackled at the same time

**Comment by Fledge68** [comment]
ok so I did some checking on this.

apparently the wii never completely shutsdown (powers off). it has 2 standby modes.
1. red light - off with wc24 off
2. yellow light - off with wc24 on

wiiflow currently does the red light. 

i'm not sure why you need wc24 on. wc24 was used to keep the news and forecast channels loaded with the current info and for receiving messages from Nintendo and other wii users via the message board.
wc24 was discontinued but RiiConnect24 ("RC24") allows the discontinued WiiConnect24 service to be used again. Currently, the service supports the News Channel, the Forecast Channel, and Wii Message Board.

do you use riiconnect24?
otherwise i see no need for standby with yellow light.

**Comment by gingerbeardman** [comment]
I use riiconnect24 and also https://wiimmfi.de/ for Mario Kart Wii notifications, which come over riiconnect24.

**Comment by Fledge68** [comment]
fixed in may 6th commit.
